clusterName: ${clusterName}
talosVersion: ${talosVersion}
kubernetesVersion: ${kubernetesVersion}
endpoint: https://${vip}:6443
domain: ${domainName}
allowSchedulingOnMasters: true
additionalApiServerCertSans:
  - k8s.${domainName}
  # - ${clusterName}.${domainName}
  - ${master1apiIP}
  - ${master2apiIP}
  - ${master3apiIP}
  - ${master1tailscaleIP}
  - ${master2tailscaleIP}
  - ${master3tailscaleIP}
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12
cniConfig:
  name: none

nodes:
  - hostname: ${master1hostname}
    ipAddress: ${master1apiIP}
    controlPlane: true
    installDisk: ${master1installDisk}
    machineDisks:
      - device: ${master1MachineDisk_mayastor}
    networkInterfaces:
      - interface: ${master1bond0aDev}
        dhcp: false
        addresses:
        - ${master1apiIP}/${apiSubnetCIDR}
        vip: 
          ip: ${vip}
        routes:
          - network: 0.0.0.0/0
            gateway: ${gateway}
      - interface: ${master1bond0bDev}
        dhcp: false
        addresses:
        - ${master1etcd2IP}/${etcd2SubnetCIDR}
      - interface: bond0
        dhcp: false
        bond:
          interfaces:
            - ${master1bond1aDev}
            - ${master1bond1bDev}
        vlans:
          - vlanId: ${realworldVLAN}
            addresses:
              - ${rwDummyIP}          
          - vlanId: ${appServiceVLAN}
            addresses:
              - ${master1appServiceIP}/${appServiceSubnetCIDR}
          - vlanId: ${etcdVLAN1}
            addresses:
              - ${master1etcd1IP}/${etcd1SubnetCIDR}
          - vlanId: ${nvmfVLAN}
            addresses:
            - ${master1nvmfIP}/${nvmfIPCIDR}

  - hostname: ${master2hostname}
    ipAddress: ${master2apiIP}
    controlPlane: true
    installDisk: ${master2installDisk}
    machineDisks:
      - device: ${master2MachineDisk_mayastor}
        label: mayastor
    networkInterfaces:
      - interface: ${master2bond0aDev}
        dhcp: false
        addresses:
        - ${master2apiIP}/${apiSubnetCIDR}
        vip: 
          ip: ${vip}
        routes:
          - network: 0.0.0.0/0
            gateway: ${gateway}
      - interface: ${master2bond0bDev}
        dhcp: false
        addresses:
        - ${master2etcd2IP}/${etcd2SubnetCIDR}
      - interface: bond0
        dhcp: false
        bond:
          interfaces:
            - ${master2bond1aDev}
            - ${master2bond1bDev}
        vlans:
          - vlanId: ${realworldVLAN}
            addresses:
              - ${rwDummyIP}          
          - vlanId: ${appServiceVLAN}
            addresses:
              - ${master2appServiceIP}/${appServiceSubnetCIDR}
          - vlanId: ${etcdVLAN1}
            addresses:
              - ${master2etcd1IP}/${etcd1SubnetCIDR}
          - vlanId: ${nvmfVLAN}
            addresses:
            - ${master2nvmfIP}/${nvmfIPCIDR}

  - hostname: ${master3hostname}
    ipAddress: ${master3apiIP}
    controlPlane: true
    installDisk: ${master3installDisk}
    machineDisks:
      - device: ${master3MachineDisk_mayastor}
    networkInterfaces:
      - interface: ${master3bond0aDev}
        dhcp: false
        addresses:
        - ${master3apiIP}/${apiSubnetCIDR}
        vip: 
          ip: ${vip}
        routes:
          - network: 0.0.0.0/0
            gateway: ${gateway}
      - interface: ${master3bond0bDev}
        dhcp: false
        addresses:
        - ${master3etcd2IP}/${etcd2SubnetCIDR}
      - interface: bond0
        dhcp: false
        bond:
          interfaces:
            - ${master3bond1aDev}
            - ${master3bond1bDev}
        vlans:
          - vlanId: ${realworldVLAN}
            addresses:
              - ${rwDummyIP}          
          - vlanId: ${appServiceVLAN}
            addresses:
              - ${master3appServiceIP}/${appServiceSubnetCIDR}
          - vlanId: ${etcdVLAN1}
            addresses:
              - ${master3etcd1IP}/${etcd1SubnetCIDR}
          - vlanId: ${nvmfVLAN}
            addresses:
            - ${master3nvmfIP}/${nvmfIPCIDR}

  - hostname: ${worker1hostname}
    nodeLabels:
      site: ${clusterSite}
      region: ${clusterRegion}
      openebs.io/csi-node: mayastor
      nvidia.com/gpu.present: true
    ipAddress: ${worker1apiIP}
    controlPlane: false
    installDisk: ${worker1installDisk}
    networkInterfaces:
      - interface: ${worker1v93apiDev}
        dhcp: false
        addresses:
        - ${worker1apiIP}/${apiSubnetCIDR}
        routes:
          - network: 0.0.0.0/0
            gateway: ${gateway}
      - interface: bond0
        dhcp: false
        bond:
          interfaces:
            - ${worker1bond1aDev}
            - ${worker1bond1bDev}
        vlans:
          - vlanId: ${appServiceVLAN}
            addresses:
              - ${worker1appServiceIP}/${appServiceSubnetCIDR}
          - vlanId: ${nvmfVLAN}
            addresses:
            - ${worker1nvmfIP}/${nvmfIPCIDR}
    schematic:
      customization:
        extraKernelArgs:
          - net.ifnames=1
          - talos.platform=metal
          - slab_nomerge
          - pti=on
          - console=ttyS0
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
            - siderolabs/nvidia-container-toolkit-production
            - siderolabs/nvidia-open-gpu-kernel-modules-production
            - siderolabs/qemu-guest-agent
            - siderolabs/tailscale
    patches:
  ## Nvidia GPU
      - |-
        - op: add
          path: /machine/kernel
          value: 
            modules:
              - name: nvidia
              - name: nvidia_uvm
              - name: nvidia_drm
              - name: nvidia_modeset
      - |-
        - op: add
          path: /machine/sysctls
          value: 
            net.core.bpf_jit_harden: 1
  ## OpenEBS Replicated
      - |-
        - op: add
          path: /machine/kubelet/extraMounts
          value:
            - destination: /var/local
              type: bind
              source: /var/local
              options:
                - bind
                - rshared
                - rw


  - hostname: ${worker2hostname}
    nodeLabels:
      site: ${clusterSite}
      region: ${clusterRegion}
      openebs.io/csi-node: mayastor
    ipAddress: ${worker2apiIP}
    controlPlane: false
    installDisk: ${worker2installDisk}
    networkInterfaces:
      - interface: ${worker2v93apiDev}
        dhcp: false
        addresses:
        - ${worker2apiIP}/${apiSubnetCIDR}
        routes:
          - network: 0.0.0.0/0
            gateway: ${gateway}
      - interface: bond0
        dhcp: false
        bond:
          interfaces:
            - ${worker2bond1aDev}
            - ${worker2bond1bDev}
        vlans:
          - vlanId: ${appServiceVLAN}
            addresses:
              - ${worker2appServiceIP}/${appServiceSubnetCIDR}
          - vlanId: ${nvmfVLAN}
            addresses:
            - ${worker2nvmfIP}/${nvmfIPCIDR}
    schematic:
      customization:
        extraKernelArgs:
          - net.ifnames=1
          - talos.platform=metal
          - slab_nomerge
          - pti=on
          - console=ttyS0
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
            - siderolabs/qemu-guest-agent
            - siderolabs/tailscale
    patches:
      - |-
        - op: add
          path: /machine/kubelet/extraMounts
          value:
            - destination: /var/local
              type: bind
              source: /var/local
              options:
                - bind
                - rshared
                - rw

controlPlane:
  nodeLabels:
    site: ${clusterSite}
    region: ${clusterRegion}
    openebs.io/engine: mayastor
  nameservers:
    - ${ns1}
    - ${ns2}
  ## enable for production
  extensionServices:
    - name: tailscale
      environment: 
        - TS_AUTHKEY=${tailscaleAuthKey}
  schematic:
    customization:
      extraKernelArgs:
        - net.ifnames=1
        - talos.platform=metal
        - slab_nomerge
        - pti=on
        - console=ttyS0
        - isolcpus=0
      systemExtensions:
        officialExtensions:
          - siderolabs/intel-ucode
          - siderolabs/tailscale
          - siderolabs/qemu-guest-agent
        ## remove for production
          - siderolabs/util-linux-tools

  patches:
    - |-
      - op: add
        path: /machine/kubelet/nodeIP
        value:
          validSubnets:
            - ${nvmfSubnet}
    - |-
      - op: replace
        path: /cluster/etcd/advertisedSubnets
        value:
          - ${etcd1Subnet}
          - ${etcd2Subnet}
    - |-
      - op: add
        path: /machine/time
        value:
          servers:
            - /dev/ptp0
          disabled: false
    - |-
      - op: add
        path: /cluster/apiServer/admissionControl
        value:
          - name: PodSecurity
            configuration:
              apiVersion: pod-security.admission.config.k8s.io/v1beta1
              kind: PodSecurityConfiguration
              exemptions:
                namespaces:
                  - openebs
   ## Mayastor worker node
    - |-
      - op: add
        path: /machine/sysctls
        value:
          vm.nr_hugepages: "1024"
    - |-
      - op: add
        path: /machine/kubelet/extraMounts
        value:
          - destination: /var/local
            type: bind
            source: /var/local
            options:
              - bind
              - rshared
              - rw


worker:
  nameservers:
    - ${ns1}
    - ${ns2}
  ## enable for production
  extensionServices:
    - name: tailscale
      environment: 
        - TS_AUTHKEY=${tailscaleAuthKey}
  ## remove for production
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
        ## remove for production
          - siderolabs/util-linux-tools
  patches:
    - |-
      - op: add
        path: /machine/kubelet/nodeIP
        validSubnets:
          - ${nvmfSubnet}
    - |-
      - op: add
        path: /machine/time
        value: 
          servers:
          ## Use hypervisor time sync
            - /dev/ptp0
          disabled: false
          # servers: 
          #   - 0.au.pool.ntp.org
          #   - 1.au.pool.ntp.org
          #   - 2.au.pool.ntp.org
          # bootTimeout: "2m0s"
    - |-
      - op: add
        path: /machine/kubelet/extraMounts
        value:
          - destination: /var/local
            type: bind
            source: /var/local
            options:
              - bind
              - rshared
              - rw
